import { Poppins } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import { NextAuthProvider } from './nextauthprovider'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'

const poppins = Poppins({ weight: ['400', '700'], subsets: ['latin'] })

/* export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */


export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body
        className={poppins.className}>

        <NextAuthProvider session={session}>
          <Providers>
            {children}
          </Providers>
        </NextAuthProvider>

      </body>
    </html>
  )
}
